Document: scidavis
Title: Debian scidavis Manual
Author: <insert document author here>
Abstract: This manual describes what scidavis is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/scidavis/scidavis.sgml.gz

Format: postscript
Files: /usr/share/doc/scidavis/scidavis.ps.gz

Format: text
Files: /usr/share/doc/scidavis/scidavis.text.gz

Format: HTML
Index: /usr/share/doc/scidavis/html/index.html
Files: /usr/share/doc/scidavis/html/*.html

  
