mat=app.importImage("blueGroper.jpg")
g1=plotContour(mat)
g1.exportToFile("groperContour.png")
g2=plotColorMap(mat)
g2.exportToFile("groperCMap.png")
g3=plotGrayScale(mat)
g3.exportToFile("groperGS.png")
app.exit()
