.TH "SciDAVis" "1" 
.SH "NAME" 
scidavis \(em Scientific Data Analysis and Visualization 
.SH "SYNOPSIS" 
.PP 
\fBscidavis\fR [\fB\fI OPTIONS \fR\fP]  [\fB\fI file_name \fR\fP]  
.SH "DESCRIPTION" 
.PP 
\fBscidavis\fR is a user-friendly data analysis and visualization program  
primarily aimed at high-quality plotting of scientific data. It  
strives to combine an intuitive, easy-to-use graphical user interface  
with powerful features such as Python scriptability. 
.SH "OPTIONS" 
.PP 
This program follows the usual GNU command line syntax, 
with long options starting with two dashes (`\-').  A summary of 
options is included below. For a complete description, run \fBscidavis \-\-help\fR. 
.IP "\fB-h\fP           \fB\-\-help\fP         " 10 
Show command line options. 
.IP "\fB-a\fP           \fB\-\-about\fP         " 10 
Show about dialog and exit. 
.IP "\fB-l=XX\fP           \fB\-\-lang=XX\fP         " 10 
Start SciDAVis in language XX ('en', 'fr', 'de', ...). 
.IP "\fB-m\fP           \fB\-\-manual\fP         " 10 
Show the SciDAVis manual in a standalone window. 
.IP "\fB-v\fP           \fB\-\-version\fP         " 10 
Print SciDAVis version and release date. 
.IP "\fB-x\fP           \fB\-\-execute\fP         " 10 
Execute the script file given as the next argument. 
.IP "\fBfile_name\fP         " 10 
Can be any .sciprj, .sciprj.gz, .qti, qti.gz, .opj, .ogm, .ogw, .ogg, .py or ASCII file.  
The file type is determined by the file's extension. 
.SH "AUTHOR" 
.PP 
This manual page was written by Tilman Benkert <thzs@gmx.net> for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Thu 18 Sep 2014, 17:46 
